site_name: a13 Wiki
markdown_extensions:
    - toc:
        permalink: true
        
theme:
  name: "material"
  palette: # 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate # 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
    - Home: 'index.md'
    - Criticisms:
      - "Thành's harem": "Criticisms/ThanhHaremCritic.md"