site_name: a13 Wiki
markdown_extensions:
    - toc:
        permalink: true

theme:
  name: "material"
  palette: # 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate # 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo : "/Images/favicon.png"
  favicon: "/Images/favicon.png"
  features:
    - navigation.sections
plugins:
  - search
  - git-revision-date-localized
  - git-authors
nav:
    - Home: 'index.md'
    - Contributing : 'contributing.md'
    - Criticisms:
      - "Thành's harem": "Criticisms/thanh-harem/index.md"
repo_url: https://github.com/datuanho2k9/a13-wiki
repo_name: wiki repo
site_description: "Wiki about a13 class"
site_author: "datuanho2k9 and more"
edit_uri: ./edit/main/docs
